let money = 75000;
let income = 'фриланс';
let addExpenses = 'интернет, такси, коммуналка';
let deposit = true;
let mission = 2000000;
let period = 12; 
console.log("type money:", typeof money);
console.log("type income:", typeof income);
console.log("type deposit:", typeof deposit);
console.log("addExpenses:", addExpenses.length);
console.log(`Период равен ${period} месяцев. Цель заработать ${mission} рублей/долларов/гривен/юани`);
console.log(addExpenses.toLocaleLowerCase().split(","));
const budgetDay = money / 30; 
console.log("budgetDay:", budgetDay);